package com.codingshuttle.razorpay.common.enums;

public enum PaymentEvent {
    AUTHORIZE_ATTEMPT,
    AUTHORIZE_SUCCESS,
    AUTHORIZE_FAILURE,
    CAPTURE_ATTEMPT,
    CAPTURE_SUCCESS,
    CAPTURE_FAILURE,
    CAPTURE_TIMEOUT,
    REFUND_ATTEMPT,
    REFUND_SUCCESS,
    REFUND_FAILURE,
    CANCEL_ATTEMPT,
    CANCEL_SUCCESS,
    CANCEL_FAILURE,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    PAYMENT_REFUND,
    PAYMENT_CANCELLATION,
    SETTLE
}
